v3.3/glfw: add openbsd support
go-gl/glfw pull request #336
Opened 2021-10-21 22:03 UTC by ilylily

partially fixes #288

simple adaptations to add openbsd support. this makes `fyne.io/fyne/v2/cmd/fyne_demo/` run on my OpenBSD-current machine. i don't have a netbsd system available, but hopefully this makes it clear which 8-ish changes a netbsd user would need to make to support that too

2021-10-22 05:06 UTC, hajimehoshi commented
Nice! This looks good to me but I'd like to defer this to other reviewers.

Can we support NetBSD in the same way?

2021-10-22 07:20 UTC, ilylily commented
netbsd support seems blocked by missing support in [go-gl/glow](https://github.com/go-gl/glow) and [godbus/dbus](https://github.com/godbus/dbus). but yes, a very similar set of changes will work for netbsd once those support it

2021-10-22 16:43 UTC, hajimehoshi commented
If there is no objection, I'll merge this.

2021-10-22 18:48 UTC, dmitshur approved these changes
Looks reasonable to me. One minor comment/question.

2021-10-22 18:48 UTC, dmitshur commented on v3.3/glfw/build.go
> +#cgo openbsd CFLAGS: -I/usr/X11R6/include
Is "/usr/X11R6/include" considered a standard include directory on OpenBSD?

2021-10-22 18:57 UTC, ilylily commented on v3.3/glfw/build.go
> +#cgo openbsd CFLAGS: -I/usr/X11R6/include
yes, that is the standard installation path for openbsd's x11 fork, which is included by default. similarly, netbsd uses `/usr/X11R7`

2021-10-22 19:13 UTC, ilylily commented on v3.3/glfw/build.go
> +#cgo openbsd CFLAGS: -I/usr/X11R6/include
actually just realized that line is unnecessary; the pkg-config covers it

2021-10-22 19:26 UTC, hajimehoshi commented on v3.3/glfw/build.go
> +#cgo openbsd LDFLAGS: -L/usr/X11R6/lib -lm -lX11 -lxcb -lXau -lXdmcp
Is `-L` needed, or is this included in pkg-config?

2021-10-22 19:31 UTC, ilylily commented on v3.3/glfw/build.go
> +#cgo openbsd LDFLAGS: -L/usr/X11R6/lib -lm -lX11 -lxcb -lXau -lXdmcp
that's actually why i thought the `-I` earlier was needed. `pkg-config --libs glfw3` only returns `-L/usr/local/lib -lglfw`, hence the need for these LDFLAGS, which are pulled from `pkg-config --cflags --libs glfw3`. which returns different output, for some reason: `-I/usr/local/include -I/usr/X11R6/include -L/usr/local/lib -L/usr/X11R6/lib -lglfw -lX11 -lxcb -lXau -lXdmcp`

2021-10-22 19:31 UTC, ilylily commented on v3.3/glfw/build.go
> +#cgo openbsd LDFLAGS: -L/usr/X11R6/lib -lm -lX11 -lxcb -lXau -lXdmcp
tl;dr yes, pkg-config is weird

2021-10-23 06:10 UTC, hajimehoshi commented
I realized that `pkg-config` for `glfw3` seems weird (#313). We don't have to need this for *BSD. I'd like to wait for #313 solved.

2021-10-23 08:23 UTC, Jacalz requested changes
Really nice work in this. I'm very interested in giving it a go running Fyne on OpenBSD :)

Can we please get the install instructions in the README updated for OpenBSD (possibly NetBSD also if that starts working)? I realise that FreeBSD isn't there but that might be outside the work of this PR, I guess?

2021-10-23 08:56 UTC, hajimehoshi commented
@ilylily would it be possible to have this change with `pkg-config` not for `glfw3` but for necessary dependencies? Depending external `glfw3` seems weird. (Then we have to address this for FreeBSD separately)

2021-10-23 15:16 UTC, hajimehoshi commented on v3.3/glfw/build.go
> +#cgo openbsd CFLAGS: -I/usr/X11R6/include
Now we have `-I/usr/X11R6/include` again but can we remove this by `pkg-config` for X? Hopefully could we remove `-L` in the same way?

2021-10-23 15:21 UTC, hajimehoshi commented
Thanks for the fix. I left a comment.

2021-10-23 15:27 UTC, hajimehoshi commented on v3.3/glfw/build.go
>  #cgo freebsd pkg-config: glfw3
One last request: can we swap the lines `openbsd pkg-config` and `freebsd pkg-config`? (probably we should keep alphabetical order here)

2021-10-23 15:28 UTC, hajimehoshi commented on v3.3/glfw/build.go
> +#cgo openbsd CFLAGS: -I/usr/X11R6/include
It looks like you have already fixed. Thanks!

2021-10-23 15:29 UTC, ilylily commented on v3.3/glfw/build.go
>  #cgo freebsd pkg-config: glfw3
got it

2021-10-23 15:30 UTC, hajimehoshi approved these changes
LGTM, thanks!

2021-10-23 15:31 UTC, merged

2021-10-23 15:56 UTC, hajimehoshi commented
Note that we should address #313 later. I hope we can use the same way as OpenBSD.

2021-10-23 16:18 UTC, Jacalz commented
As I said earlier, I also think we should update the README with installation instructions for OpenBSD.

2021-10-23 16:20 UTC, hajimehoshi commented
> As I said earlier, I also think we should update the README with installation instructions for OpenBSD.

Oh sorry I missed that.

@ilylily Could you create a PR to update README? Thanks,